FROM python:3.10
WORKDIR /app/api
COPY api/ ./

RUN pip install -r ./requirements.txt
RUN playwright install --with-deps
ENV FLASK_ENV=production
ENV PYTHONPATH=/app

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "app:app"]
