services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: store-price-comparison-api

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: store-price-comparison-client
    ports:
      - "3000:80"
